--------------------------CREATE TABLE CTXSYS.DR$OBJECT_ATTRIBUTE-------------------------------------
DROP TABLE ODS_DATA.O_CBI_DR$OBJECT_ATTRIBUTE_CK ;
CREATE MULTISET TABLE ODS_DATA.O_CBI_DR$OBJECT_ATTRIBUTE_CK 
 (OAT_ID decimal(22)   NOT NULL,
 OAT_CLA_ID decimal(22)   NULL,
 OAT_OBJ_ID decimal(22)   NULL,
 OAT_ATT_ID decimal(22)   NULL,
 OAT_NAME varchar(30) CHARACTER SET UNICODE  NULL,
 OAT_DESC varchar(80) CHARACTER SET UNICODE  NULL,
 OAT_REQUIRED char(1)   NULL,
 OAT_SYSTEM char(1)   NULL,
 OAT_STATIC char(1)   NULL,
 OAT_DATATYPE char(1)   NULL,
 OAT_DEFAULT varchar(500) CHARACTER SET UNICODE  NULL,
 OAT_VAL_MIN decimal(22)   NULL,
 OAT_VAL_MAX decimal(22)   NULL,
 OAT_LOV char(1)   NULL,
 IN_ID BIGINT  NULL ,
 MD5ALL VARCHAR(50) CHARACTER SET UNICODE  NULL ,
 IN_MD5ALL VARCHAR(50) CHARACTER SET UNICODE  NULL )
 PRIMARY INDEX (
OAT_REQUIRED
);
--------------------------CREATE TABLE SYS.SYSTEM_PRIVILEGE_MAP-------------------------------------
DROP TABLE ODS_DATA.O_CBI_SYSTEM_PRIVILEGE_MAP_CK ;
CREATE MULTISET TABLE ODS_DATA.O_CBI_SYSTEM_PRIVILEGE_MAP_CK 
 (PRIVILEGE decimal(22)  TITLE 'Numeric privilege type code' NOT NULL,
 NAME varchar(40) CHARACTER SET UNICODE TITLE 'Name of the type of privilege' NOT NULL,
 PROPERTY decimal(22)  TITLE 'Property flag of privilege like not export this privilege, etc' NOT NULL,
 IN_ID BIGINT  NULL ,
 MD5ALL VARCHAR(50) CHARACTER SET UNICODE  NULL ,
 IN_MD5ALL VARCHAR(50) CHARACTER SET UNICODE  NULL )
 PRIMARY INDEX (
PRIVILEGE,NAME,PROPERTY
);
COMMENT ON TABLE SYS.SYSTEM_PRIVILEGE_MAP IS 'Description table for privilege type codes.  Maps privilege  type numbers to type names';
--------------------------CREATE TABLE SYS.AW$AWCREATE10G-------------------------------------
DROP TABLE ODS_DATA.O_CBI_AW$AWCREATE10G_CK ;
CREATE MULTISET TABLE ODS_DATA.O_CBI_AW$AWCREATE10G_CK 
 (PS# decimal(10)   NULL,
 GEN# decimal(10)   NULL,
 EXTNUM decimal(8)   NULL,
 AWLOB varchar(1234) CHARACTER SET UNICODE  NULL,
 OBJNAME varchar(256) CHARACTER SET UNICODE  NULL,
 PARTNAME varchar(256) CHARACTER SET UNICODE  NULL,
 IN_ID BIGINT  NULL ,
 MD5ALL VARCHAR(50) CHARACTER SET UNICODE  NULL ,
 IN_MD5ALL VARCHAR(50) CHARACTER SET UNICODE  NULL )
 PRIMARY INDEX (
OBJNAME
);
--------------------------CREATE TABLE SYS.HS_BULKLOAD_VIEW_OBJ-------------------------------------
DROP TABLE ODS_DATA.O_CBI_HS_BULKLOAD_VIEW_OBJ_CK ;
CREATE MULTISET TABLE ODS_DATA.O_CBI_HS_BULKLOAD_VIEW_OBJ_CK 
 (SCHEMA_NAME varchar(30) CHARACTER SET UNICODE  NULL,
 VIEW_NAME varchar(30) CHARACTER SET UNICODE  NULL,
 TEMP_OBJ_ID decimal(22)   NULL,
 IN_ID BIGINT  NULL ,
 MD5ALL VARCHAR(50) CHARACTER SET UNICODE  NULL ,
 IN_MD5ALL VARCHAR(50) CHARACTER SET UNICODE  NULL )
 PRIMARY INDEX (
TEMP_OBJ_ID
);
--------------------------CREATE TABLE SYS.AW$EXPRESS-------------------------------------
DROP TABLE ODS_DATA.O_CBI_AW$EXPRESS_CK ;
CREATE MULTISET TABLE ODS_DATA.O_CBI_AW$EXPRESS_CK 
 (PS# decimal(10)   NULL,
 GEN# decimal(10)   NULL,
 EXTNUM decimal(8)   NULL,
 AWLOB varchar(1234) CHARACTER SET UNICODE  NULL,
 OBJNAME varchar(256) CHARACTER SET UNICODE  NULL,
 PARTNAME varchar(256) CHARACTER SET UNICODE  NULL,
 IN_ID BIGINT  NULL ,
 MD5ALL VARCHAR(50) CHARACTER SET UNICODE  NULL ,
 IN_MD5ALL VARCHAR(50) CHARACTER SET UNICODE  NULL )
 PRIMARY INDEX (
GEN#,OBJNAME
);
--------------------------CREATE TABLE CTXSYS.DR$THS_PHRASE-------------------------------------
DROP TABLE ODS_DATA.O_CBI_DR$THS_PHRASE_CK ;
CREATE MULTISET TABLE ODS_DATA.O_CBI_DR$THS_PHRASE_CK 
 (THP_ID decimal(22)   NOT NULL,
 THP_THSID decimal(22)   NULL,
 THP_PHRASE varchar(256) CHARACTER SET UNICODE  NOT NULL,
 THP_QUALIFY varchar(256) CHARACTER SET UNICODE  NULL,
 THP_NOTE varchar(2000) CHARACTER SET UNICODE  NULL,
 THP_RINGID decimal(22)   NULL,
 IN_ID BIGINT  NULL ,
 MD5ALL VARCHAR(50) CHARACTER SET UNICODE  NULL ,
 IN_MD5ALL VARCHAR(50) CHARACTER SET UNICODE  NULL )
 PRIMARY INDEX (
THP_ID
);
--------------------------CREATE TABLE TEST.EMPSHOP_ORDER_RECORD-------------------------------------
DROP TABLE ODS_DATA.O_CBI_EMPSHOP_ORDER_RECORD_CK ;
CREATE MULTISET TABLE ODS_DATA.O_CBI_EMPSHOP_ORDER_RECORD_CK 
 (ID decimal(20)  TITLE '主键ID' NOT NULL,
 ORDER_ID decimal(20)  TITLE '订单ID' NULL,
 GOODS_ID decimal(20)  TITLE '货物ID' NULL,
 GOODS_NAME varchar(300) CHARACTER SET UNICODE TITLE '货物名称' NULL,
 GOODS_NUMBER decimal(10)  TITLE '货物数量' NULL,
 PRICE decimal(10,2)  TITLE '单价' NULL,
 BOOK_PERSON_ID varchar(30) CHARACTER SET UNICODE TITLE '预订者ID' NULL,
 BOOK_STATUS decimal(2)  TITLE '预定状态(0 退货，1正常， 2系统退货)' NULL,
 GOODS_STATUS decimal(2)  TITLE '缺货状态（0 缺货，1正常）' NULL,
 RECEIVE_STATUS decimal(2)  TITLE '领取状态(0 未领取,1领取)' NULL,
 DEPBOOKSTATUS decimal(2)  TITLE '0代表的是没有进行部门缴款，1代表的是进行了部门缴款' NULL,
 COMBOOKSTATUS decimal(2)  TITLE '1代表的是没有进行公司缴款，0代表的是进行了公司缴款' NULL,
 CANCLE_NUM varchar(20) CHARACTER SET UNICODE TITLE '此字段无效，不再使用' NULL,
 ODS_ETL_TIME timestamp(6)   NOT NULL,
 IN_ID BIGINT  NULL ,
 MD5ALL VARCHAR(50) CHARACTER SET UNICODE  NULL ,
 IN_MD5ALL VARCHAR(50) CHARACTER SET UNICODE  NULL )
 PRIMARY INDEX (
ID
);
COMMENT ON TABLE TEST.EMPSHOP_ORDER_RECORD IS '订单明细表';
--------------------------CREATE TABLE SYS.DUAL-------------------------------------
DROP TABLE ODS_DATA.O_CBI_DUAL_H_CK ;
CREATE MULTISET TABLE ODS_DATA.O_CBI_DUAL_H_CK 
 (DUMMY varchar(1) CHARACTER SET UNICODE  NULL,
 IN_ID BIGINT  NULL ,
 MD5ALL VARCHAR(50) CHARACTER SET UNICODE  NULL ,
 IN_MD5ALL VARCHAR(50) CHARACTER SET UNICODE  NULL )
 PRIMARY INDEX (
DUMMY
);
--------------------------CREATE TABLE SYS.TABLE_PRIVILEGE_MAP-------------------------------------
DROP TABLE ODS_DATA.O_CBI_TABLE_PRIVILEGE_MAP_CK ;
CREATE MULTISET TABLE ODS_DATA.O_CBI_TABLE_PRIVILEGE_MAP_CK 
 (PRIVILEGE decimal(22)  TITLE 'Numeric privilege (auditing option) type code' NOT NULL,
 NAME varchar(40) CHARACTER SET UNICODE TITLE 'Name of the type of privilege (auditing option)' NOT NULL,
 IN_ID BIGINT  NULL ,
 MD5ALL VARCHAR(50) CHARACTER SET UNICODE  NULL ,
 IN_MD5ALL VARCHAR(50) CHARACTER SET UNICODE  NULL )
 PRIMARY INDEX (
PRIVILEGE,NAME
);
COMMENT ON TABLE SYS.TABLE_PRIVILEGE_MAP IS 'Description table for privilege (auditing option) type codes.  Maps privilege (auditing option) type numbers to type names';
